experiment:
  episode_num: 1
  replay_save_interval: 16
  # debug: True

env:
  map_size: 80
  player_num: 24
  npc_num: 128
  horizon: 256
  fog_onset: 32
  fog_speed: 0.2
  fog_final_size: 16
  disable_stone: False
  individual_num: 24
  competitive_num: 0
  cooperative_num: 0



agent:
  model_name: "llama"
  enable_llm_thinking: False
  use_information_reduction: False
  use_strategy: False
  use_interaction_memory: False
  allow_give_action: True
  max_execute_step: 10
  max_verify_time: 0
  share_strategy: False
  share_game_rule_module: False
